const express = require('express')
const router = express.Router()
const c = require('../controllers/adminCommerceController')
const adminUserController = require('../controllers/adminUserController')
const adminAiController = require('../controllers/adminAiController')
const exportController = require('../controllers/exportController')
const { requireLogin } = require('../middleware/auth')
const { requireRole } = require('../middleware/role')
const { rateLimit } = require('../middleware/rateLimit')

router.use(requireLogin)
router.get('/users', requireRole('admin','super_admin'), c.users)
router.get('/users/:username', requireRole('admin','super_admin'), adminUserController.detail)
router.post('/users/:username/access', requireRole('super_admin'), c.updateUser)
router.post('/users/:username/balance', requireRole('admin','super_admin'), c.adjustBalance)
router.get('/vouchers', requireRole('staff','admin','super_admin'), c.vouchers)
router.post('/vouchers', requireRole('admin','super_admin'), c.createVoucher)
router.post('/vouchers/:id/toggle', requireRole('admin','super_admin'), c.toggleVoucher)
router.get('/flash-sales', requireRole('staff','admin','super_admin'), c.flashSales)
router.post('/flash-sales', requireRole('admin','super_admin'), c.createFlashSale)
router.get('/tickets', requireRole('support','staff','admin','super_admin'), c.tickets)
router.get('/tickets/:id', requireRole('support','staff','admin','super_admin'), c.ticket)
router.post('/tickets/:id/reply', requireRole('support','staff','admin','super_admin'), c.replyTicket)
router.post('/tickets/:id/close', requireRole('support','staff','admin','super_admin'), c.closeTicket)
router.get('/audit', requireRole('admin','super_admin'), c.auditLogs)
router.get('/insights', requireRole('staff','admin','super_admin'), c.insights)
router.get('/export/:type', requireRole('admin','super_admin'), c.exportData)
router.get('/export-excel/:type', requireRole('admin','super_admin'), exportController.exportExcel)
router.post('/ai/query', requireRole('staff','admin','super_admin'), rateLimit({ max: 30, keyPrefix: 'admin-ai' }), adminAiController.query)

module.exports = router
