const express = require('express')
const router = express.Router()
const adminController = require('../controllers/adminController')
const adminTopupController = require('../controllers/adminTopupController')
const adminOrderController = require('../controllers/adminOrderController')
const adminInventoryController = require('../controllers/adminInventoryController')
const { requireLogin } = require('../middleware/auth')
const { requireRole } = require('../middleware/role')

router.use(requireLogin)
router.get('/', requireRole('support','kitchen','staff','admin','super_admin'), adminController.showAdminHome)
router.get('/orders', requireRole('kitchen','staff','admin','super_admin'), adminController.listOrders)
router.get('/orders/update/:id', requireRole('kitchen','staff','admin','super_admin'), (req,res)=>res.redirect('/admin/orders'))
router.post('/orders/update/:id', requireRole('kitchen','staff','admin','super_admin'), adminOrderController.updateStatus)
router.get('/categories', requireRole('staff','admin','super_admin'), adminController.showCategories)
router.post('/categories/add', requireRole('staff','admin','super_admin'), adminController.addCategory)
router.post('/categories/delete/:id', requireRole('admin','super_admin'), adminController.deleteCategory)
router.get('/stats', requireRole('staff','admin','super_admin'), adminController.showStats)
router.get('/foods', requireRole('kitchen','staff','admin','super_admin'), adminController.listFoods)
router.get('/foods/create', requireRole('staff','admin','super_admin'), adminController.showCreateFood)
router.post('/foods', requireRole('staff','admin','super_admin'), adminController.createFood)
router.get('/foods/add', requireRole('staff','admin','super_admin'), adminController.showAddFood)
router.post('/foods/add', requireRole('staff','admin','super_admin'), adminController.addFood)
router.post('/foods/delete/:id', requireRole('admin','super_admin'), adminController.deleteFood)
router.post('/foods/:id/delete', requireRole('admin','super_admin'), adminController.deleteFood)
router.get('/foods/edit/:id', requireRole('staff','admin','super_admin'), adminController.showEditFood)
router.post('/foods/edit/:id', requireRole('staff','admin','super_admin'), adminController.updateFood)
router.get('/foods/:id/edit', requireRole('staff','admin','super_admin'), adminController.showEditFood)
router.post('/foods/:id/edit', requireRole('staff','admin','super_admin'), adminController.updateFood)
router.get('/inventory', requireRole('kitchen','staff','admin','super_admin'), adminInventoryController.list)
router.post('/inventory/:id', requireRole('kitchen','staff','admin','super_admin'), adminInventoryController.update)
router.get('/topups', requireRole('admin','super_admin'), adminTopupController.list)
router.post('/topups/:id/approve', requireRole('admin','super_admin'), adminTopupController.approve)
router.post('/topups/:id/reject', requireRole('admin','super_admin'), adminTopupController.reject)

module.exports = router
