const express = require('express')
const router = express.Router()
const adminController = require('../controllers/adminController')
const adminTopupController = require('../controllers/adminTopupController')
const { requireLogin } = require('../middleware/auth')
const { requireAdmin } = require('../middleware/admin')

router.use(requireLogin, requireAdmin)

router.get('/', adminController.showAdminHome)
router.get('/orders', adminController.listOrders)
router.get('/orders/update/:id', (req, res) => res.redirect('/admin/orders'))
router.post('/orders/update/:id', adminController.updateOrderStatus)
router.get('/categories', adminController.showCategories)
router.post('/categories/add', adminController.addCategory)
router.post('/categories/delete/:id', adminController.deleteCategory)
router.get('/stats', adminController.showStats)
router.get('/foods', adminController.listFoods)
router.get('/foods/create', adminController.showCreateFood)
router.post('/foods', adminController.createFood)
router.get('/foods/add', adminController.showAddFood)
router.post('/foods/add', adminController.addFood)
router.post('/foods/delete/:id', adminController.deleteFood)
router.post('/foods/:id/delete', adminController.deleteFood)
router.get('/foods/edit/:id', adminController.showEditFood)
router.post('/foods/edit/:id', adminController.updateFood)
router.get('/foods/:id/edit', adminController.showEditFood)
router.post('/foods/:id/edit', adminController.updateFood)
router.get('/topups', adminTopupController.list)
router.post('/topups/:id/approve', adminTopupController.approve)
router.post('/topups/:id/reject', adminTopupController.reject)

module.exports = router
