const express=require('express')
const router=express.Router()
const {chat,feedback,correction,search,combo,parse,cartCalc,alternatives,reviewAnalysis,showChat}=require('../controllers/aiController')
const {requireAdmin}=require('../middleware/admin')
const {rateLimit}=require('../middleware/rateLimit')
const foodAssistant=require('../lib/foodAssistant')
const aiLimit=rateLimit({max:40,windowMs:60_000,keyPrefix:'ai'})

router.get('/',showChat)
router.post('/chat',aiLimit,foodAssistant.middleware,chat)
router.post('/feedback',rateLimit({max:30,keyPrefix:'ai-feedback-page'}),feedback)
router.post('/correction',requireAdmin,rateLimit({max:20,keyPrefix:'ai-correction-page'}),correction)
router.post('/search',aiLimit,search)
router.post('/combo',aiLimit,combo)
router.post('/parse',aiLimit,parse)
router.post('/cart-calc',aiLimit,cartCalc)
router.get('/alternatives/:id',aiLimit,alternatives)
router.post('/alternatives',aiLimit,alternatives)
router.get('/review-analysis/:id',aiLimit,reviewAnalysis)
router.post('/review-analysis',aiLimit,reviewAnalysis)
module.exports=router
