const express = require('express')
const router = express.Router()

const foodRoutes = require('./foodRoutes')
const userRoutes = require('./userRoutes')
const cartRoutes = require('./cartRoutes')
const orderRoutes = require('./orderRoutes')
const postRoutes = require('./postRoutes')
const adminRoutes = require('./adminRoutes')
const addressRoutes = require('./addressRoutes')
const apiRoutes = require('./apiRoutes')
const commerceRoutes = require('./commerceRoutes')
const adminCommerceRoutes = require('./adminCommerceRoutes')
const paymentRoutes = require('./paymentRoutes')
const chatController = require('../controllers/chatController')
const foodAssistant = require('../lib/foodAssistant')
const aiRoutes = require('./aiRoutes')

router.post('/chat', express.json(), foodAssistant.middleware, chatController.chat)
router.use('/', foodRoutes)
router.use('/', userRoutes)
router.use('/', cartRoutes)
router.use('/', orderRoutes)
router.use('/', postRoutes)
router.use('/', addressRoutes)
router.use('/', commerceRoutes)
router.use('/', paymentRoutes)
router.use('/admin', adminRoutes)
router.use('/admin', adminCommerceRoutes)
router.use('/api', apiRoutes)
router.use('/ai', aiRoutes)

module.exports = router
