const express = require('express')
const router = express.Router()
const userController = require('../controllers/userController')
const walletController = require('../controllers/walletController')
const passwordRecovery = require('../controllers/passwordRecoveryController')
const { requireLogin } = require('../middleware/auth')
const { rateLimit } = require('../middleware/rateLimit')
const { registerValidation, loginValidation, handleValidationErrors } = require('../middleware/validation')

const otpVerifyMiddleware = process.env.NODE_ENV === 'development'
  ? (req, res, next) => next()
  : rateLimit({ max: 10, windowMs: 10 * 60_000, keyPrefix: 'otp' })

router.get('/register', userController.showRegister)
router.post('/register', rateLimit({ max: 5, windowMs: 15 * 60_000, keyPrefix: 'register' }), registerValidation, handleValidationErrors, userController.register)
router.get('/register/verify', userController.showVerify)
router.post('/register/verify', otpVerifyMiddleware, userController.verifyRegister)
router.get('/login', userController.showLogin)
router.post('/login', rateLimit({ max: 10, windowMs: 10 * 60_000, keyPrefix: 'login' }), loginValidation, handleValidationErrors, userController.login)
router.get('/forgot-password', passwordRecovery.showForgot)
router.post('/forgot-password', rateLimit({ max: 5, windowMs: 15 * 60_000, keyPrefix: 'forgot' }), passwordRecovery.requestReset)
router.get('/reset-password', passwordRecovery.showReset)
router.post('/reset-password', rateLimit({ max: 10, windowMs: 15 * 60_000, keyPrefix: 'reset' }), passwordRecovery.resetPassword)
router.post('/logout', requireLogin, userController.logout)
router.get('/logout', requireLogin, userController.logout)
router.get('/profile', requireLogin, userController.showProfile)
router.get('/profile/edit', requireLogin, userController.showEditProfile)
router.post('/profile/edit', requireLogin, userController.updateProfile)

router.get('/wallet', requireLogin, walletController.showWallet)
router.get('/wallet/top-up', requireLogin, walletController.showWallet)
router.post('/wallet/top-up', requireLogin, walletController.createTopUp)
router.get('/bank', requireLogin, walletController.showBank)
router.post('/payment-success', requireLogin, walletController.confirmTransfer)

module.exports = router
