const express = require('express')
const router = express.Router()
const userController = require('../controllers/userController')
const walletController = require('../controllers/walletController')
const { requireLogin } = require('../middleware/auth')
const { registerValidation, loginValidation, handleValidationErrors } = require('../middleware/validation')

router.get('/register', userController.showRegister)
router.post('/register', registerValidation, handleValidationErrors, userController.register)
router.get('/register/verify', userController.showVerify)
router.post('/register/verify', userController.verifyRegister)
router.get('/login', userController.showLogin)
router.post('/login', loginValidation, handleValidationErrors, userController.login)
router.post('/logout', requireLogin, userController.logout)
router.get('/logout', requireLogin, userController.logout)
router.get('/profile', requireLogin, userController.showProfile)
router.get('/profile/edit', requireLogin, userController.showEditProfile)
router.post('/profile/edit', requireLogin, userController.updateProfile)

router.get('/wallet', requireLogin, walletController.showWallet)
router.get('/wallet/top-up', requireLogin, walletController.showWallet)
router.post('/wallet/top-up', requireLogin, walletController.createTopUp)
router.get('/bank', requireLogin, walletController.showBank)
router.post('/payment-success', requireLogin, walletController.confirmTransfer)

module.exports = router
