const foodModel = require('../models/foodModels')
const commerce = require('./commerceService')

function norm(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase().trim()}
function tokens(value){return norm(value).split(/[^a-z0-9]+/).filter(w=>w.length>1)}
function parseBudget(text){const s=norm(text);const m=s.match(/(?:ngan sach|duoi|khong qua|toi da|tam|khoang)?\s*(\d+(?:[.,]\d+)?)\s*(k|nghin|ngan|000|d)?/i);if(!m)return null;let v=Number(String(m[1]).replace(',','.'));if(/k|nghin|ngan/i.test(m[2]||'')||v<1000)v*=1000;return Math.round(v)}
function parsePeople(text){const m=norm(text).match(/(\d+)\s*(?:nguoi|người)/);return m?Math.max(1,Math.min(20,Number(m[1]))):null}
function isFoodQuestion(message){const s=norm(message);return /(goi y|mon gi|an gi|tim mon|mon nao|do an|thuc an|menu|gia bao nhieu|duoi \d|nguyen lieu|cay|it dau|giam can|protein|hai san|bo|ga|com|bun|mi|pizza|sushi|combo|nguoi)/.test(s)}
function updatePreferences(prefs,text){const s=norm(text);const next={...(prefs||{})};const budget=parseBudget(text),people=parsePeople(text);if(/khong an cay|khong cay|so cay/.test(s))next.noSpicy=true;if(/an cay|thich cay/.test(s)&&!/khong/.test(s))next.noSpicy=false;if(/an chay|vegetarian/.test(s))next.vegetarian=true;if(/khong an chay/.test(s))next.vegetarian=false;if(/it dau|giam can|healthy|it calo/.test(s))next.healthy=true;if(/protein|tap gym/.test(s))next.highProtein=true;if(budget)next.budget=budget;if(people)next.people=people;return next}
function hasPreferenceStatement(text){return /(khong an cay|khong cay|so cay|an chay|khong an chay|it dau|giam can|healthy|protein|tap gym|ngan sach|\d+\s*nguoi)/.test(norm(text))}
function scoreFood(food,message,budget,prefs={}){const hay=norm([food.title,food.description,food.ingredients,food.category_name].filter(Boolean).join(' '));const words=tokens(message).filter(w=>!['mon','goi','tim','cho','toi','minh','an','duoc','khong','nhieu','mot','nguoi'].includes(w));let score=0;for(const w of words)if(hay.includes(w))score+=w.length>=5?4:2;if(budget&&Number(food.price)<=budget)score+=5;if(budget&&Number(food.price)>budget)score-=12;const s=norm(message);if((/giam can|it calo|it dau|nhe bung/.test(s)||prefs.healthy)&&/rau|salad|uc ga|ca|it dau|healthy/.test(hay))score+=5;if((/protein|tap gym/.test(s)||prefs.highProtein)&&/bo|ga|ca|trung|hai san|protein/.test(hay))score+=5;if(/cay/.test(s)&&/cay|sa te|ot|spicy/.test(hay))score+=4;if(prefs.noSpicy&&/cay|sa te|ot|spicy/.test(hay))score-=20;if(prefs.vegetarian&&!/rau|nam|chay|dau hu|trai cay|salad/.test(hay))score-=15;return score}
async function priced(food){const sale=await commerce.currentSaleForFood(food.id);return{...food,price:sale?Number(sale.sale_price):Number(food.price||0),original_price:Number(food.price||0),flash_sale:sale||null}}

async function makeCombo(foods,budget,people,prefs,message){const ranked=[];for(const raw of foods){const food=await priced(raw);const score=scoreFood(food,message,budget,prefs);if(score>-10&&Number(food.price)>0)ranked.push({food,score})}ranked.sort((a,b)=>b.score-a.score||a.food.price-b.food.price);const selected=[];let spent=0;const target=Math.max(1,people||2);for(const x of ranked){if(selected.length>=Math.min(6,target*2))break;if(spent+x.food.price<=budget){selected.push(x.food);spent+=x.food.price}}return{selected,spent}}

async function recommend(message,prefs={}){
  const foods=await foodModel.getFoods({limit:100});if(!Array.isArray(foods)||!foods.length)return null
  const budget=parseBudget(message)||prefs.budget||null,people=parsePeople(message)||prefs.people||1,s=norm(message)
  if(/combo|cho \d+ nguoi|\d+ nguoi/.test(s)&&budget){const {selected,spent}=await makeCombo(foods,budget,people,prefs,message);if(selected.length){return{ok:true,intent:'food_combo',type:'foods',reply:`Combo cho ${people} người trong ngân sách ${budget.toLocaleString('vi-VN')}đ: ${selected.map(f=>f.title).join(', ')}. Tổng khoảng ${spent.toLocaleString('vi-VN')}đ.`,cards:selected.map(f=>({id:f.id,title:f.title,price:f.price,image:f.image||'',description:f.description||''})),data:selected,quickActions:[{label:'Combo rẻ hơn',value:`Combo ${people} người dưới ${Math.max(10000,budget-20000)}đ`},{label:'Đổi khẩu vị',value:'Gợi ý combo khác'}]}}
  }
  if(!isFoodQuestion(message))return null
  const effectiveBudget=budget&&people>1?Math.floor(budget/Math.max(1,people)):budget
  const prepared=[];for(const raw of foods)prepared.push(await priced(raw))
  const ranked=prepared.map(food=>({food,score:scoreFood(food,message,effectiveBudget,prefs)})).filter(x=>x.score>0||(!effectiveBudget&&tokens(message).length<=4)).sort((a,b)=>b.score-a.score||a.food.price-b.food.price).slice(0,5).map(x=>x.food)
  if(!ranked.length)return{ok:true,intent:'food_recommendation',type:'text',reply:budget?`Mình chưa thấy món phù hợp trong mức ${budget.toLocaleString('vi-VN')}đ với sở thích hiện tại. Bạn có thể tăng ngân sách hoặc đổi yêu cầu.`:'Mình chưa xác định được món phù hợp. Hãy nói ngân sách, số người, nguyên liệu hoặc khẩu vị.',cards:[],data:[],quickActions:[]}
  const notes=[];if(prefs.noSpicy)notes.push('không cay');if(prefs.vegetarian)notes.push('ăn chay');if(prefs.healthy)notes.push('ưu tiên nhẹ/ít dầu');if(prefs.highProtein)notes.push('ưu tiên protein')
  return{ok:true,intent:'food_recommendation',type:'foods',reply:`Mình gợi ý ${ranked.length} món${notes.length?' theo sở thích '+notes.join(', '):''}:\n${ranked.map((f,i)=>`${i+1}. ${f.title} — ${Number(f.price).toLocaleString('vi-VN')}đ`).join('\n')}`,cards:ranked.map(f=>({id:f.id,title:f.title,price:f.price,image:f.image||'',description:f.description||'',originalPrice:f.original_price})),data:ranked,quickActions:[{label:'Dưới 50k',value:'Gợi ý món dưới 50k'},{label:'Combo 2 người',value:'Combo 2 người dưới 100k'},{label:'Nhiều protein',value:'Gợi ý món nhiều protein'}]}
}

async function middleware(req,res,next){try{const message=req.body&&(req.body.message||req.body.text||req.body.question);if(!message)return next();const before=req.session.aiFoodPrefs||{};const prefs=updatePreferences(before,message);req.session.aiFoodPrefs=prefs;const response=await recommend(message,prefs);if(response)return res.json({...response,memory:prefs});if(hasPreferenceStatement(message)&&JSON.stringify(before)!==JSON.stringify(prefs))return res.json({ok:true,intent:'preference_memory',type:'text',reply:'Mình đã ghi nhớ sở thích này trong phiên chat để gợi ý món phù hợp hơn.',cards:[],data:[],quickActions:[{label:'Gợi ý món',value:'Gợi ý món cho tôi'},{label:'Tạo combo',value:`Tạo combo ${prefs.people||2} người dưới ${prefs.budget||100000}đ`}],memory:prefs});return next()}catch(_){return next()}}
module.exports={norm,parseBudget,parsePeople,isFoodQuestion,updatePreferences,recommend,middleware}
