const db=require('../config/db')
const fs=require('fs/promises')
const path=require('path')

let ready=false
async function ensureSchema(){if(ready)return;await db.ready();try{await db.query(`CREATE TABLE IF NOT EXISTS rag_documents (id INTEGER PRIMARY KEY AUTOINCREMENT,source_type TEXT NOT NULL,source_id TEXT NOT NULL,content TEXT NOT NULL,embedding TEXT DEFAULT '',updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,UNIQUE(source_type,source_id))`)}catch(_){await db.query(`CREATE TABLE IF NOT EXISTS rag_documents (id INT AUTO_INCREMENT PRIMARY KEY,source_type VARCHAR(50) NOT NULL,source_id VARCHAR(255) NOT NULL,content LONGTEXT NOT NULL,embedding LONGTEXT,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uniq_source(source_type,source_id))`)}ready=true}
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
function tokens(s){return new Set(norm(s).split(' ').filter(x=>x.length>1))}
function lexical(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/Math.sqrt(A.size*B.size)}
function cosine(a,b){if(!Array.isArray(a)||!Array.isArray(b)||a.length!==b.length||!a.length)return 0;let dot=0,aa=0,bb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i]}return aa&&bb?dot/(Math.sqrt(aa)*Math.sqrt(bb)):0}
async function embed(text){const url=process.env.AI_EMBEDDING_URL;if(!url)return null;const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json',...(process.env.AI_EMBEDDING_TOKEN?{authorization:`Bearer ${process.env.AI_EMBEDDING_TOKEN}`}:{})},body:JSON.stringify({model:process.env.AI_EMBEDDING_MODEL||'nomic-embed-text',input:text,prompt:text})});if(!response.ok)throw new Error(`Embedding provider ${response.status}`);const j=await response.json();return j.embedding||j.data?.[0]?.embedding||j.embeddings?.[0]||null}
async function upsert(sourceType,sourceId,content,vector){await ensureSchema();const [rows]=await db.query('SELECT id FROM rag_documents WHERE source_type=? AND source_id=?',[sourceType,String(sourceId)]);const encoded=Array.isArray(vector)?JSON.stringify(vector):'';if(rows.length)await db.query('UPDATE rag_documents SET content=?,embedding=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',[content,encoded,rows[0].id]);else await db.query('INSERT INTO rag_documents(source_type,source_id,content,embedding) VALUES(?,?,?,?)',[sourceType,String(sourceId),content,encoded])}
async function rebuild(){await ensureSchema();const docs=[];const [foods]=await db.query('SELECT id,title,description,ingredients,price FROM foods');for(const f of foods)docs.push({type:'food',id:f.id,content:`${f.title}. ${f.description||''}. Nguyên liệu: ${f.ingredients||''}. Giá ${Number(f.price||0)} đồng.`});const [corrections]=await db.query('SELECT id,question,admin_correction FROM ai_corrections ORDER BY id DESC LIMIT 500').catch(()=>[[]]);for(const c of corrections)docs.push({type:'correction',id:c.id,content:`Câu hỏi: ${c.question}. Trả lời đã xác minh: ${c.admin_correction}`});try{const raw=await fs.readFile(path.join(__dirname,'..','data','faq.json'),'utf8');const faq=JSON.parse(raw);for(const [i,item] of faq.entries())docs.push({type:'faq',id:item.id||i+1,content:`${item.question||''} ${item.answer||''}`})}catch(_){};for(const doc of docs){let vector=null;try{vector=await embed(doc.content)}catch(_){}await upsert(doc.type,doc.id,doc.content,vector)}return docs.length}
async function search(query,limit=5){await ensureSchema();const [rows]=await db.query('SELECT * FROM rag_documents ORDER BY id DESC LIMIT 2000');let qv=null;try{qv=await embed(query)}catch(_){}return rows.map(r=>{let vec=null;try{vec=r.embedding?JSON.parse(r.embedding):null}catch(_){};const ls=lexical(query,r.content),vs=qv&&vec?cosine(qv,vec):0;return{...r,score:qv&&vec?Math.max(vs,ls*.8):ls}}).filter(x=>x.score>=Number(process.env.RAG_MIN_SCORE||0.36)).sort((a,b)=>b.score-a.score).slice(0,Math.min(Number(limit)||5,10))}
async function middleware(req,res,next){try{const message=String(req.body?.message||req.body?.question||'').trim();if(message.length<4)return next();const hits=await search(message,3);if(!hits.length||hits[0].score<Number(process.env.RAG_ANSWER_SCORE||0.55))return next();const answer=hits.map((h,i)=>`${i+1}. ${h.content}`).join('\n');return res.json({ok:true,intent:'RAG_KNOWLEDGE',type:'rag',reply:`Mình tìm thấy thông tin liên quan trong dữ liệu MINI FOOD:\n${answer}`,data:hits.map(h=>({sourceType:h.source_type,sourceId:h.source_id,score:Number(h.score.toFixed(3))})),cards:[],quickActions:[]})}catch(_){next()}}
module.exports={ensureSchema,rebuild,search,middleware,embed}
